export const regions = [
    {regionName: "Ang Mo Kio"},
    {regionName: "Bedok"},
    {regionName: "Benoi"},
    {regionName: "Bishan"},
    {regionName: "Boon Lay"},
    {regionName: "Bukit Batok"},
    {regionName: "Bukit Merah"},
    {regionName: "Bukit Panjang"},
    {regionName: "Bukit Timah"},
    {regionName: "Central Water Catchment"},
    {regionName: "Changi"},
    {regionName: "Changi Bay"},
    {regionName: "Choa Chu Kang"},
    {regionName: "Clementi"},
    {regionName: "Geylang"},
    {regionName: "Ghim Moh"},
    {regionName: "Gul"},
    {regionName: "Holland Road"},
    {regionName: "Hougang"},
    {regionName: "Jurong East"},
    {regionName: "Jurong Island"},
    {regionName: "Jurong West"},
    {regionName: "Kallang"},
    {regionName: "Kent Ridge"},
    {regionName: "Lim Chu Kang"},
    {regionName: "Mandai"},
    {regionName: "Marina Bay"},
    {regionName: "Marina Centre"},
    {regionName: "Marine Parade"},
    {regionName: "Nanyang"},
    {regionName: "Newton"},
    {regionName: "North-Eastern Islands"},
    {regionName: "Novena"},
    {regionName: "Orchard"},
    {regionName: "Outram"},
    {regionName: "Pandan Gardens"},
    {regionName: "Pasir Laba"},
    {regionName: "Pasir Ris"},
    {regionName: "Paya Lebar"},
    {regionName: "Pioneer"},
    {regionName: "Punggol"},
    {regionName: "Queenstown"},
    {regionName: "Raffles Place"},
    {regionName: "River Valley"},
    {regionName: "Rochor"},
    {regionName: "Seletar"},
    {regionName: "Sembawang"},
    {regionName: "Sengkang"},
    {regionName: "Sentosa"},
    {regionName: "Serangoon"},
    {regionName: "Simpang"},
    {regionName: "Southern Islands"},
    {regionName: "Sungei Kadut"},
    {regionName: "Tampines"},
    {regionName: "Tanglin"},
    {regionName: "Tanjong Pagar"},
    {regionName: "Teban Gardens"},
    {regionName: "Tengah"},
    {regionName: "Thomson"},
    {regionName: "Toa Payoh"},
    {regionName: "Toh Tuck"},
    {regionName: "Tuas"},
    {regionName: "Tuas South"},
    {regionName: "West Coast"},
    {regionName: "Western Islands"},
    {regionName: "Western Water Catchment"},
    {regionName: "Woodlands"},
    {regionName: "Yishun"}
];

