// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const DELETE_CLEANER = 'DELETE_CLEANER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI'
// Data reducer types
export const SET_CLEANERS = 'SET_CLEANERS';
export const SET_CLEANER = 'SET_CLEANER';
export const LIKE_CLEANER = 'LIKE_CLEANER';
export const CANCELLIKE_CLEANER = 'CANCELLIKE_CLEANER';
export const UNLIKE_CLEANER = 'UNLIKE_CLEANER';
export const CANCELUNLIKE_CLEANER = 'CANCELUNLIKE_CLEANER';
export const SET_COMMENTS = 'SET_COMMENTS';
export const SET_COMMENT = 'SET_COMMENT';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const SET_HISTORIES ='SET_HISTORIES';
